### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by semillerimages** [PavelBlend/blender_jet_fluids_addon#1]
My 2.79b shows in the console this error message and the addon does not show up...

fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\semiller\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\semiller\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\semiller\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\addon.py'
Modules Installed () from 'E:\\Templates\\00001-blenderaddons\\blender_jet_fluids_addon-master.zip' into 'C:\\Users\\semiller\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'

**Comment by PavelBlend** [comment]
Where did you download the addon?
Judging by the name of the archive (blender_jet_fluids_addon-master.zip) you downloaded the source.
Addon need to download from the releases page:
https://github.com/PavelBlend/blender_jet_fluids_addon/releases
Download the archive (jet_fluids_demo_0_0_4.zip) and repeat the installation.
If this does not help, then let me know.

**Comment by semillerimages** [comment]
Ahh, I'm not so familiar with GitHub yet :) Problem solved. Thank you!
